# Generated by Django 2.2.1 on 2019-09-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='store_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_to_text', models.CharField(max_length=1000)),
            ],
        ),
    ]
