# Generated by Django 2.2.1 on 2019-09-10 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_store_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='store_text',
            new_name='speech',
        ),
    ]
