# Generated by Django 2.2.1 on 2019-09-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_auto_20190909_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='store_syn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syndrome_store', models.CharField(max_length=1000)),
            ],
        ),
    ]
